steps:
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/wayira-api:$SHORT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/wayira-api:latest',
      '.'
    ]

  # Subir la imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wayira-api:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wayira-api:latest']

  # Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wayira-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/wayira-api:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'RIOT_API_KEY=${_RIOT_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/wayira-api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/wayira-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY

